theme: jekyll-theme-cayman
title: Breve Internet and Privacy Tips
description: Internet privacy and security recommendations

 <div id="google_translate_element"></div>  
      
    <script type="text/javascript">  
        function googleTranslateElementInit() {  
            new google.translate.TranslateElement( 
                {pageLanguage: 'en'},  
                'google_translate_element' 
            );  
        }  
    </script>  
      
    <script type="text/javascript" src= 
"https://translate.google.com/translate_a/element.js? 
        cb=googleTranslateElementInit"> 
    </script>  
